import os
OUTPUT = r'C:\Users\ginja\cast-science-resources\scripts\create_all_lessons_L02_L10.py'
def w(f, text):
    f.write(text + chr(10))
with open(OUTPUT, 'a', encoding='utf-8') as f:
    w(f, '    # SIMULATION OBSERVATIONS')
    w(f, '    add_section_header(doc, "Simulation Observations")')
    w(f, '    add_name_date_line(doc)')
    w(f, '    p = doc.add_paragraph()')
    w(f, '    p.add_run("Run each scenario in ModelIt and record your observations.").font.size = DocxPt(11)')
    w(f, '    doc.add_paragraph()')
    w(f, '    for i, (sc_name, sc_instruction) in enumerate(scenarios, 1):')
    w(f, '        add_section_header(doc, f"Scenario {i}: {sc_name}", level=2)')
    w(f, '        p = doc.add_paragraph()')
    w(f, '        run = p.add_run("Settings: ")')
    w(f, '        run.bold = True')
    w(f, '        run.font.size = DocxPt(11)')
    w(f, '        p.add_run(sc_instruction).font.size = DocxPt(11)')
    w(f, '        p2 = doc.add_paragraph()')
    w(f, '        p2.add_run("Prediction: What do you think will happen?").font.size = DocxPt(11)')
    w(f, '        p2.runs[0].italic = True')
    w(f, '        add_response_box(doc, 2)')
    w(f, '        p3 = doc.add_paragraph()')
    w(f, '        run = p3.add_run("Observation: What actually happened? Describe what you saw on the graph.")')
    w(f, '        run.bold = True')
    w(f, '        run.font.size = DocxPt(11)')
    w(f, '        add_response_box(doc, 3)')
    w(f, '    doc.add_page_break()')
    w(f, '')
    w(f, '    # RESEARCH AND EXTEND')
    w(f, '    add_section_header(doc, "Research and Extend")')
    w(f, '    add_name_date_line(doc)')
    w(f, '    p = doc.add_paragraph()')
    w(f, '    p.add_run("Real systems are more complex than our basic model. Extend your model with new components\!").font.size = DocxPt(11)')
    w(f, '    doc.add_paragraph()')
    w(f, '    add_section_header(doc, "Possible New Components:", level=2)')
    w(f, '    extensions = config.get("extensions", [')
    w(f, '        "Temperature - how does heat affect the system?",')
    w(f, '        "Time of Year - do seasons matter?",')
    w(f, '        "Human Activity - how do people affect the system?",')
    w(f, '    ])')
    w(f, '    for ex in extensions:')
    w(f, '        p = doc.add_paragraph()')
    w(f, '        run = p.add_run(f"  *  {ex}")')
    w(f, '        run.font.size = DocxPt(11)')
    w(f, '    doc.add_paragraph()')
    w(f, '    add_section_header(doc, "My Extension:", level=2)')
    w(f, '    p = doc.add_paragraph()')
    w(f, '    run = p.add_run("New component I want to add: ")')
    w(f, '    run.bold = True')
    w(f, '    run.font.size = DocxPt(11)')
    w(f, '    p.add_run("________________________________").font.size = DocxPt(11)')
    w(f, '    p2 = doc.add_paragraph()')
    w(f, '    run = p2.add_run("How does it connect to existing components? Draw and explain:")')
    w(f, '    run.bold = True')
    w(f, '    run.font.size = DocxPt(11)')
    w(f, '    ext_sketch = doc.add_table(rows=1, cols=1)')
    w(f, '    ext_sketch.style = "Table Grid"')
    w(f, '    ext_sketch.rows[0].cells[0].text = chr(10) * 6')
    w(f, '    doc.add_paragraph()')
    w(f, '    p3 = doc.add_paragraph()')
    w(f, '    run = p3.add_run("What evidence or reasoning supports these connections?")')
    w(f, '    run.bold = True')
    w(f, '    run.font.size = DocxPt(11)')
    w(f, '    add_response_box(doc, 4)')
    w(f, '    doc.add_page_break()')
    w(f, '')
    w(f, '    # REFLECTION QUESTIONS')
    w(f, '    add_section_header(doc, "Reflection Questions")')
    w(f, '    add_name_date_line(doc)')
    w(f, '    p = doc.add_paragraph()')
    w(f, '    p.add_run("Answer these questions after completing all activities.").font.size = DocxPt(11)')
    w(f, '    doc.add_paragraph()')
    w(f, '    reflections = [')
    w(f, '        f"1. Answer the Big Question: {big_question} Use evidence from your model\!",')
    w(f, '        "2. What surprised you most from running the simulations?",')
    w(f, '        "3. Which relationship in the model do you think is most important? Why?",')
    w(f, '        "4. How could you use what you learned to solve a real-world problem?",')
    w(f, '        "5. What questions do you still have after today?",')
    w(f, '    ]')
    w(f, '    for q in reflections:')
    w(f, '        p = doc.add_paragraph()')
    w(f, '        run = p.add_run(q)')
    w(f, '        run.bold = True')
    w(f, '        run.font.size = DocxPt(11)')
    w(f, '        add_response_box(doc, 4)')
    w(f, '    doc.add_page_break()')
    w(f, '')
    w(f, '    # STEM CHALLENGE')
    w(f, '    add_section_header(doc, f"STEM CHALLENGE: {stem_title}")')
    w(f, '    add_name_date_line(doc)')
    w(f, '    add_section_header(doc, "YOUR MISSION", level=2)')
    w(f, '    p = doc.add_paragraph()')
    w(f, '    p.add_run(stem_mission).font.size = DocxPt(11)')
    w(f, '    doc.add_paragraph()')
    w(f, '    add_section_header(doc, "THE SCENARIO", level=2)')
    w(f, '    p = doc.add_paragraph()')
    w(f, '    p.add_run(stem_scenario).font.size = DocxPt(11)')
    w(f, '    doc.add_paragraph()')
    w(f, '    add_section_header(doc, "ENGINEERING DESIGN THINKING", level=2)')
    w(f, '    stem_qs = config.get("stem_questions", [')
    w(f, '        "What problem are you trying to solve?",')
    w(f, '        "What constraints or limitations do you have?",')
    w(f, '        "What does your model tell you about the best solution?",')
    w(f, '    ])')
    w(f, '    for q in stem_qs:')
    w(f, '        p = doc.add_paragraph(style="List Bullet")')
    w(f, '        p.add_run(q).font.size = DocxPt(11)')
    w(f, '    doc.add_paragraph()')
    w(f, '    add_section_header(doc, "MY DESIGN", level=2)')
    w(f, '    p = doc.add_paragraph()')
    w(f, '    p.add_run("Draw your design below:").font.size = DocxPt(10)')
    w(f, '    p.runs[0].italic = True')
    w(f, '    design_box = doc.add_table(rows=1, cols=1)')
    w(f, '    design_box.style = "Table Grid"')
    w(f, '    design_box.rows[0].cells[0].text = chr(10) * 10')
    w(f, '    doc.add_paragraph()')
    w(f, '    add_section_header(doc, "EXPLAIN YOUR DESIGN", level=2)')
    w(f, '    p = doc.add_paragraph()')
    w(f, '    run = p.add_run("Why did you design it this way? Use scientific reasoning from your model\!")')
    w(f, '    run.bold = True')
    w(f, '    run.font.size = DocxPt(11)')
    w(f, '    add_response_box(doc, 5)')
    w(f, '')
    w(f, '    doc.save(output_path)')
    w(f, '    print(f"[OK] Created: {output_path}")')
    w(f, '    return output_path')
    w(f, '')
print('Part 6d done')
